- tsconfig.json
This PR changes where TypeScript looks for the `data` directory to keep the GitHub Actions scripts working.
(Ignore the branch name)
> Update `tsconfig.json` to point to parent directory for project data

- src/pages/events/[page_id].astro
- src/pages/index.astro
Updates the autogenerated home and event pages to not rely on page data being included directly in the `project.json` file in the data repo.
(Note: Many of the changes logged below are cosmetic, as I am now using Prettier to format automatically on save and I wasn't when these files were first committed -- my bad!)
> Updating to new project.json schema

- src/pages/events/[page_id].astro
- src/pages/tags/detail.astro
- src/pages/tags/index.astro
Cleans up (hopefully) some errors that arise in the case that there are no annotation files present in the data, since `Astro.glob` throws an error when it finds no matches. ([Controversial but apparently intentional](https://github.com/withastro/astro/issues/5091) behavior on Astro's part.)
> Better error handling if no annotation/event files

- package-lock.json
- package.json
This PR upgrades Astro to the latest version, mainly because we need https://github.com/withastro/astro/pull/11264 that comes in 4.11.
> Upgrade Astro from 4.8 to 4.15

- src/components/Player.tsx
- src/components/PlayerWithAnnotations.astro
- src/pages/events/[pageUuid].astro
Adds a `sticky` prop to the `PlayerWithAnnotations` component that sets that positioning of the player so that it sticks to the top of the page when scrolled. Addresses https://github.com/AVAnnotate/admin-client/issues/80.
> Made player on auto event pages sticky

- src/pages/tags/detail.astro
- src/pages/tags/index.astro
- Updates the way tag names are being displayed so that `_uncategorized_` correctly appears as `Uncategorized`.
- Adds the "see detail" button to the tag index page.
- Fixes a bug that was preventing event labels from being displayed correctly on the tag details page.
> Minor fixes to tag index

- src/components/AnnotationUI/Annotations.astro
- src/components/AnnotationUI/TagFilter.tsx
- Addresses Issue #16 where the category filter checkbox wasn't working correctly.
- Tag filter will now group tags together if they have the same (case insensitive) category name, rather than separating e.g. `speaker` and `Speaker`.
> Debugging tag filters

- src/components/Event.astro
- src/content/config.ts
This PR fixes an issue where the `description` field was incorrectly marked as required in the event schema, causing build failures for projects containing events that didn't have descriptions.
> Make event description optional in schema

- src/components/RichText/Leaves/Link.astro
Links weren't showing up because the `Link` component was checking whether the element was italicized instead of whether it's a link. Oops! This PR fixes that and adds styling to make the links blue and underlined (it seems like Tailwind overrides the default browser styles for links).
> Fix link display in rich text component

- src/layouts/Layout.astro
- src/pages/index.astro
This PR updates the logic in the `Layout` component to prioritize showing the `users` project field (which optionally contains a string entered by the user) in place of the creator's GitHub name if it exists.
> Show user-provided name as project creator if it exists

- src/components/RichText/RichTextElement.astro
- src/components/TableOfContents.astro
- src/pages/index.astro
- src/utils/pages.ts
- refactors the existing page list from the homepage into a new `TableOfContents` Astro component (with underline styling added to match Figma)
- updates the homepage to display a custom home page if the user has disabled autogeneration for their project's homepage; otherwise, we display the original hardcoded one
> Custom homepages with Table of Contents component

- package.json
- src/components/Container.astro
- src/components/EventViewer/AnnotationUI/Annotations/Annotation.astro
- src/components/EventViewer/AnnotationUI/Annotations/AnnotationHeader.astro
- src/components/EventViewer/AnnotationUI/Annotations/index.astro
- src/components/EventViewer/AnnotationUI/TagFilter.tsx
- src/components/EventViewer/AudioEvent.astro
- src/components/EventViewer/VideoEvent.astro
- src/components/EventViewer/index.astro
- src/layouts/Layout.astro
- src/store.ts
- updates the styling of the filter menu to match the latest from Figma
- adds set filtering (see below)
- adds a `rm -rf ./dist` prefix to the build step because `astro check` always tries to check the `dist` folder like Wile E. Coyote running into a wall, and runs out of memory doing so. This will make it less annoying for us to run the build process locally which will hopefully have the downstream effect of fewer build errors getting merged.
(I don't know why every set in this event is called "default" but that's how it is in the JSON)
This feature handles a few different situations:
1. When an event has only one set (i.e. the default set), we don't show the set filters at all.
2. When the user hasn't selected any sets in the filter menu, we show all sets (this is consistent with the …
> Update filter menu and add set filtering

- src/style/player.css
This PR adds a minimum height to the `iframe` element that embedded YouTube videos come in. Previously, we applied styles to `video` elements which worked fine for non-YT videos, but YT comes in `iframes` instead.
They also have slightly different behavior than `video` tags when deciding their height - YT seems to stick to 150px unless you specifically set a `height` property, so here we set it to 500px.
> Fix styling for embedded YouTube videos

- package-lock.json
- package.json
- src/components/EventViewer/AnnotationUI/AnnotationHeader.astro
- src/components/EventViewer/AnnotationUI/Annotations/AnnotationNanostorePopulator.tsx
- src/components/EventViewer/AnnotationUI/Annotations/index.astro
- src/components/EventViewer/AnnotationUI/TextSearch.tsx
- src/components/EventViewer/AudioEvent.astro
- src/components/EventViewer/ConditionalContainer.astro
- src/components/EventViewer/VideoEvent.astro
- src/components/EventViewer/index.astro
- src/components/Player/index.tsx
- src/components/Player/types.ts
- src/components/RichText/RichTextElement.astro
- src/pages/events/[pageUuid].astro
- src/pages/pages/[pageUuid].astro
- src/store.ts
- src/types/slate.ts
This PR, originally intended to be a small feature update to enable clip embeds, ended up being a bit of an adventure with all the refactoring/restructuring I had to do to in order to actually get the clip feature done.
* tons of fixes for embedded events
* the autoscroll feature now scrolls within its container when inside an event, instead of scrolling the entire page
* styling fixes for both audio and video embeds
* increased the `progressInterval` of the player from 50ms to 250ms (we needed more frequent updates on the admin client because we show millisecond-level timestamps there) and removed the check in the clientside `Annotations` component code that rate limited the state listener (no longer needed with significantly less frequent state updates)
* updated `react-player` to their …
> Event clip embeds

- src/components/Sidebar.tsx
- src/components/TableOfContents.astro
* adds indentation to child pages in the `TableOfContents` component
* fixes bad linking logic for the homepage where it was being treated like an event (I'm not sure how it was able to work before?)
> Indent child pages in Table of Contents

- src/components/Sidebar.tsx
- src/components/TableOfContents.astro
- src/content/config.ts
- src/pages/events/[pageUuid].astro
- src/pages/pages/[pageUuid].astro
- src/utils/pages.ts
This PR makes use of a previous [PR](https://github.com/AVAnnotate/admin-client/pull/150) on the admin-client which creates human readable slugs for Pages.  The client will use the slugs if the exist, otherwise it will continue using the UUIDs.
> Slugify paths

- dynamic-astro-config.js
- package-lock.json
This PR reverts a recent change in the config that told Astro to look in `../data` instead of `src/content` for project data, restoring the `src/content` value. This doesn't make a difference for production deployments (the data exists in both places there) but avoids the need for extra config on local dev builds.
It also includes some autoformatting from Prettier and a change to my `package-lock` that came up when I ran `npm i`.
> Fix project data path

- src/components/Header.astro
- src/components/Sidebar.tsx
- src/pages/events/[eventSlug].astro
- src/pages/events/[pageSlug].astro
- src/pages/pages/[pageSlug].astro
This PR fixes a bug that prevented pages with slugs from being correctly identified as the current page by the Sidebar component.
Edit: On a quick re-read, all this PR ended up doing is renaming a few things. I don't think there's any actual changed logic here. But I could definitely replicate #58 when I started and it's definitely fixed on this branch. Something must have changed?
> Fix sidebar current page detection logic

- src/components/EventViewer/AnnotationUI/Annotations/Annotation.astro
- src/components/EventViewer/AnnotationUI/Annotations/AnnotationNanostorePopulator.tsx
- src/components/EventViewer/AnnotationUI/Annotations/index.astro
- src/components/EventViewer/AudioEvent.astro
- src/components/EventViewer/AudioFilePicker.tsx
- src/components/EventViewer/VideoEvent.astro
- src/components/Player/index.tsx
- src/store.ts
- src/types/index.ts
This PR updates the audio event viewer to support multiple files, including several use cases:
* When an event contains only 1 AV file, behavior is completely unchanged.
* When an event contains multiple AV files, there is now a list above the player that allows the user to switch between them. (I've also added the `file` attribute to the annotation filtering logic so only annotations from the current file will display)
* When an embedded event contains the entire event *and* the event has more than one AV file, the AV file picker is displayed in the embed.
* When an embedded event contains a *clip*, the picker is not displayed in the embed (because the clip is of only one AV file)
* When an embedded event contains the entire event and the event has only one AV file, no picker is …
> Multiple AV file support for audio events

- src/components/Header.astro
- src/components/Sidebar.tsx
- adds the index page to the sidebar
- fixes the actual bug at the root of #58 (checking whether the current page's slug matches the homepage's slug would always return `true` because the homepage didn't have a slug)
- adds an `overflow-y` rule to the sidebar so it now scrolls if its content goes off the page, addressing #67
> Add index page to sidebar + styling fixes

- src/components/EventViewer/AnnotationUI/Annotations/index.astro
- src/components/EventViewer/AnnotationUI/TagFilter.tsx
- src/components/RichText/index.astro
This PR fixes a couple bugs and might fix a third:
* adds a `min-width` to prevent annotation set checkboxes from getting squished horizontally when the set name is really long
* wraps rich text into a `div` and applies `overflow-wrap: anywhere`, which allows the browser to break long words (such as URLs) down the middle to wrap into a new line instead of overflowing, without treating normal-length words any differently. This seems to be the default behavior in Firefox, but Blink and WebKit browsers allow long links to extend the width of their containers by default. In the big picture, this fixes the issue where the annotations pane would sometimes get really wide despite the `2fr 1fr` grid style.
* changes the `AnnotationNanostorePopulator` from `client:only` to `client:load` so it …
> Video player fixes

- src/components/EventViewer/AnnotationUI/Annotations/Annotation.astro
- src/components/EventViewer/AnnotationUI/Annotations/AnnotationNanostorePopulator.tsx
- src/components/EventViewer/AnnotationUI/Annotations/index.astro
- src/components/EventViewer/AudioFilePicker.tsx
- src/components/EventViewer/VideoEvent.astro
- src/components/EventViewer/VideoFilePicker.tsx
- adds the ability to switch between AV file, when applicable, on video events
- uses a new Canvas-based component to display the video thumbnails (my Topsters experience came in handy!)
- the thumbnail will not be shown if anything goes wrong when trying to load it (the title and duration will still be shown)
- fixes an issue where annotations from all files were being shown on initial page load instead of just the ones for the current file
The different cases listed in #63 also apply here.
(The second AV here begins with a black screen - the thumbnail is correct)
> Multiple AV file support for video events

- src/components/EventViewer/VideoEvent.astro
This PR fixes a bug from #68 where the `event.data.description` field wasn't being null-checked before being rendered, resulting in a crash if the field was `null`. It also fixes what seems to be an oversight where the file picker wouldn't be displayed if the user had configured an embedded event to not include a description.
> Better null checking for event description field

- src/components/EventViewer/VideoFilePicker.tsx
- tsconfig.json
A recent PR disabled strict mode, probably to get around some build errors. But when strict mode is disabled, Zod considers all content fields to be optional, causing even more build errors. This PR re-enables strict mode and adds some null checks in the `VideoFilePicker` to make TS happy.
> Re-enable TypeScript strict mode

- src/components/Player/index.tsx
During page transitions on production builds, the video often fails to render because the state is not updating correctly and the code was unable to retrieve the file URL.  This PR changes the flow somewhat to ensure that at least one AV file URL is present on page loads.
> Video disappearing bug

- src/components/Sidebar.tsx
This PR fixes an issue where pages without slugs were failing to be detected as the current page. This was happening because the sidebar was only comparing the page's `slug` attribute. Pages without slugs are given path names using their UUIDs, so the sidebar needed to compare UUIDs too.
> Fix sidebar current page detection for pages without slugs

- src-aviary/pages/index.astro
- src/components/EventViewer/AnnotationUI/AnnotationHeader.astro
- src/components/EventViewer/AnnotationUI/Annotations/index.astro
- src/components/EventViewer/AnnotationUI/TagFilter.tsx
- src/components/EventViewer/AnnotationUI/TextSearch.tsx
- src/components/EventViewer/AudioEvent.astro
- src/components/EventViewer/AudioFilePicker.tsx
- src/components/EventViewer/ComparisonFilePicker.tsx
- src/components/EventViewer/VideoEvent.astro
- src/components/EventViewer/VideoEventCompare.astro
- src/components/Player/index.tsx
- src/layouts/Layout.astro
- src/pages/tags/detail/[category]/[tag].astro
- src/utils/player.ts
This PR replaces all instances of `client:only` with `client:load`, addressing #45.
The difference here is that `client:only` components are fetched by the browser at runtime, through a separate network request for each component contained within what Astro calls an island. This causes a slight delay, especially in deployed environments, as the browser makes dozens of requests for each Astro island.
`client:load` will include the component in the initial statically generated page, so it's already there on page load. It's then *hydrated* with whatever props/data are provided at runtime. This is only possible if the component has the props and data it needs to render at the time of page generation, and if the component's first clientside render has the same DOM tree as the server-side …
> Replace all `client:only` props with `client:load`

- src/components/RichText/RichTextElement.astro
By default, browsers assign a height of 0 to empty `p` elements (`<p></p>`), so empty new lines created in the rich text editor didn't seem to display here in the project client. This PR updates the `RichText` component to require a minimum height on `p` elements that matches the line height so those empty paragraphs will take up vertical space on the page.
> Update spacing for `p` tags in rich text blocks

- src/components/EventViewer/AnnotationUI/TagFilter.tsx
This PR is an attempt to fix a crash that only (sporadically) occurs in production. The minified error messages we get on prod were enough to narrow it down to one particular spot, `thisPlayer.sets.length` in the tag filter component.
`thisPlayer.sets` should never be undefined, as it's populated by the `defaultState` object when the player state isn't available yet. But I can't imagine that this error could be happening anywhere else. I don't see a place where the `sets` value could be anything other than an array.
So this PR adds a `?` to make it `thisPlayer.sets?.length`. We'll see if the bug continues to happen...
> Possible annotation crash fix

- package-lock.json
- package.json
- src/components/EventViewer/AnnotationUI/TagFilter.tsx
- src/store.ts
This PR adds the `@nanostores/logger` package to try to get to the bottom of #82, which only happens in production 😒
> Add nanostore logging

- src/components/EventViewer/AnnotationUI/Annotations/AnnotationNanostorePopulator.tsx
- src/components/EventViewer/PlayerStateNanostorePopulator.tsx
Thanks to the logging from #88, I might have found the cause of #82.
The two React components we use to manage the nanostore for some of the clientside config were updating it with syntax like:
```ts
useEffect(() => {
$pagePlayersState.setKey(props.playerId, {
...store[props.playerId],
isEmbed: props.isEmbed,
avFileUuid: props.initialFile,
});
}, [props.playerId, props.isEmbed]);
```
It appears that `store[props.playerId]` was being evaluated as soon as the component mounted. If this component mounted before the JS that populates the initial store was finished running, then `store[props.playerId]` would resolve to either `undefined` or `{}`. (Surprisingly, `{ ...undefined }` doesn't seem to cause a JS error - it's treated as equivalent to `{}`).
The large number of sets/annotations on the …
> Use the correct state value in populator components

- src/content/config.ts
This PR removes the requirement for a file_url for AV files from the Astro Content schema.
> Allow the file_url to be null

- src/components/RichText/RichTextElement.astro
This goes along with https://github.com/AVAnnotate/admin-client/pull/194 by enabling support for the new `line-break` element in the `RichText` Astro component.
> Add `line-break` node support to RichText

- src/components/TagUtils/AnnotationSpectrum.astro
After some digging, I figured out that the cause of #102 was that the index page wasn't sorting annotations chronologically. This PR adds a `sort` call that fixes the issue.
> Sort annotations on index pages

- src/utils/tags.ts
This PR updates the `getTagDisplay` function used across the index pages to capitalize every word in a tag, instead of just the first word. The previous behavior looked weird when people's names were used as tags.
> Capitalize every word in tag names on index pages

- src/components/EventViewer/AnnotationUI/Annotations/Annotation.astro
This PR fixes a styling issue that occurred in Chrome across all annotation list components, where the timestamp text was overflowing its horizontal bounds and overlapping with the annotation text.
See https://github.com/AVAnnotate/project-client/issues/98
> Fix timestamp spacing in annotation list

- src/components/RichText/RichTextElement.astro
This PR fixes two of the styling issues from #115 
- fixes bullet points (and numbers, for numbered list) not displaying
- adds a gap between columns in grids
> Page styling fixes

- src/components/EventViewer/AudioFilePicker.tsx
- src/components/Player/index.tsx
- Removes the duration indicator from the `AudioFilePicker` component, as it is redundant for online files (also shown in the player) and is a confusing dummy value for offline files;
- Hides the audio player in the case that there is no file URL for a given file, replacing it with brief text indicating that the file is offline. (Open to comments on exactly what that text should read, obviously! And for where the string should live; probably ideally not just hard coded into the component file. In a translation file?)
This addresses https://github.com/AVAnnotate/admin-client/issues/221#issuecomment-2554780048 .
> UI for audio file picker & offline files

- src/components/RichText/RichTextElement.astro
Adds some rather clunky CSS to correctly align image elements in the rich text components -- previously only the `text-align` style was being applied, which was not placing images properly. The way I've done it here is by adjusting the image margins based on whether it's left/right/center-aligned, which seems to work fine. Could also (maybe more elegantly?) be done by making the `div` surrounding the `img` have `display: flex` and `justify-content: center` but I wasn't sure about ripple effects from messing with the `display` attribute so did it this way for now.
This addresses one of the bullet points of Issue #115 .
> Added styling for image alignment

- src/components/RichText/RichTextElement.astro
- src/components/RichText/RichTextLeaf.astro
- Adjusts the `RichTextLeaf` component so that extraneous spaces are no longer getting appended to formatted text elements.
- Also seems to include a couple of commits that @camdendotlol made yesterday (this branch was based off his `styling-fixes` branch), so he can comment on whether those changes are ready to go (some adjustment to list styling and grid spacing, it seems).
The space issue addresses one of the bullet points of Issue #115 .
> Removing weird extra spaces; other styling tweaks

- src/pages/tags/detail/[category]/[tag].astro
- src/pages/tags/detail/[category]/index.astro
- src/pages/tags/detail/index.astro
- src/utils/tags.ts
Quick and dirty fix for the fact that annotations sets are being displayed in an apparently nonsensical order on the various tag detail pages. This fix should have them ordered alphabetically by event label and then alphabetically by set name.
> Order of annotation sets in tag detail pages

- src/components/EventViewer/AudioFilePicker.tsx
- src/components/Player/index.tsx
Updates the layout for events with multiple AV files, following the requests in Issue #126, making a dropdown select rather than a list, and modifying the text for offline files that displays instead of the player.
> Adjustments to multifile event UI

- src/components/EventViewer/AudioEvent.astro
- src/components/EventViewer/VideoEvent.astro
As per https://github.com/AVAnnotate/admin-client/issues/223, adds the event citation, if defined, at the bottom of the auto-generated event pages.
This is a simple implementation without going deep into making it configurable whether or not to display the citation for a given event; should that be something we let users specific in the admin CMS, or is it all right to assume that if they fill in the citation field it should be displayed? Also, should anything more be done with formatting or labeling it? (It seems that field is currently a plaintext string, not rich text; should it be italicized here or anything?)
> Adding citation to bottom of events

- src/components/EventViewer/AudioEvent.astro
- src/components/EventViewer/VideoEvent.astro
- src/components/RichText/RichTextElement.astro
- src/pages/index.astro
- src/pages/pages/[pageSlug].astro
- src/style/main.css
Adds a case for the type `horizontal-spacer` to the rich text renderer, and adds a bit of vertical padding around basic paragraph elements to better match the visual layout of the RTE in the admin client.
This is related to Issue #127, which refers to specifically this page: https://tanyaclement.github.io/znh-1939/pages/introduction/ . Is the paragraph spacing something that we in fact want in general on all projects, or just something we want for that page? (Personally I like having the spacing between paragraphs, but just want to make sure since this is a general fix not just related to that project.)
> Added horizontal separator and paragraph padding

- src/components/TableOfContents.astro
In some cases the link to the project home page is not being successfully hidden from the autogenerated table of contents; the issue seems to be that the `Astro.url.pathname` value does not always include the trailing `/`, which was causing the build process to fail to identify the home page as the home page. Just stripping the `/` characters before comparing is a bit of a brute force fix but seems like it should be reliable.
> Remove home page link from autogenerated ToC

- src/components/EventViewer/AnnotationUI/Annotations/index.astro
- src/components/Player/index.tsx
- src/store.ts
- Addresses https://github.com/AVAnnotate/admin-client/issues/265
There was a bug that did not handle multiple clips on the same page well. Also an issue with the duration calculation for the player.
> Fix multiple clips on same page

- src/components/EventViewer/AnnotationUI/Annotations/Annotation.astro
- Addresses https://github.com/AVAnnotate/admin-client/issues/259]
This problem was actually fixed by an earlier[PR](https://github.com/AVAnnotate/project-client/pull/142). The problem was caused by multiple clips on the same page (in this case multiple sets). This PR just tries to ensure that the scrolled-to annotation appears above the footer.
> Small fix to scrolling

- src/pages/tags/detail/[category]/[tag].astro
This PR fixes #169 and #134. The issue is that the player state was never being initialized, so the annotation state was stuck falling back to the default state with no annotations. The fix was to add a `PlayerStateNanostorePopulator` to the component. I also removed the `AnnotationNanostorePopulator` that appears directly in the tag page because the `Annotations` component handles that state on its own (I think this was one of the changes I made during the redesign).
> Fix missing `PlayerStateNanostorePopulator` on tag page

- src/components/EventViewer/AnnotationUI/Annotations/Annotation.astro
- src/components/EventViewer/AnnotationUI/Annotations/index.astro
- src/components/EventViewer/AudioFile.astro
- src/components/EventViewer/VideoEventCompare.astro
- src/components/EventViewer/VideoFile.astro
- src/components/Player/index.tsx
- src/pages/tags/detail/[category]/[tag].astro
- src/store.ts
- src/utils/player.ts
This PR addresses #177, which was a more complicated bug than I expected.
The root issue is that every AV player within an `EventViewer` instance shares the same `playerId` value, while the nanostore assumes that a `playerId` refers to only one file (e.g. with values like `isPlaying` and `position`). When the user clicked the play button, the nanostore for the `playerId` was set to `isPlaying`, which applied to both AV files within that event.
Ideally we'd refactor `isPlaying` and similar state to be per-file rather than per-event, but that would be a decent amount of work so I made the fix as narrow as possible since we're in overage.
* changes `isPlaying` from a boolean to an optional string value (the UUID of the file currently playing)
* updates all instances of `isPlaying` throughout …
> Fix `isPlaying` incorrectly syncing between AV files

- src/components/EventViewer/AnnotationUI/Annotations/index.astro
- src/components/EventViewer/AudioFile.astro
- src/components/EventViewer/PlayerStateNanostorePopulator.tsx
- src/components/EventViewer/index.astro
This PR adds logic to the `Annotation` component that hides annotations if they don't fall within the clip range (if a clip range exists).
This bug was a little strange because it seems like the filter functionality didn't exist at all prior to this PR, even though it seems like someone would have noticed it a lot sooner if that were the case. The annotations have `data-start` and `data-end` HTML attributes but nothing was reading them. We should definitely have Steve test this change because there's a high chance of weirdness here.
> Filter annotations for clips

- src/components/EventViewer/AnnotationUI/Annotations/index.astro
- src/store.ts
Autoscroll seems to have been broken because a client-side script was trying to fill the `annotationStarts` array in the player state based on the already-existing value for `annotationStarts`. Since this value wasn't populated anywhere else, the annotations component wasn't aware of the annotation list when determining which ones to scroll to.
> Fix autoscroll not working
