AVAnnotate/project-client

astro.config.mjs
src/components/Header.astro
src/components/Player.tsx
src/pages/events/[page_id].astro
src/pages/index.astro
src/pages/tags/detail.astro
src/pages/tags/index.astro

Updates how the base URL used in internal links is defined, to pull from the `dynamicConfig` object in dev but from the `project.slug` field in production, in order to work better with the GitHub action setup.
(Also some more formatting updates from Prettier.)

Updated baseurl variable in production env

---

src/components/AnnotationUI/Annotations.astro
src/components/AnnotationUI/TagFilter.tsx
src/components/AnnotationUI/TextSearch.tsx
src/components/PlayerWithAnnotations.astro
src/store.ts
tailwind.config.mjs

- Adds text and tag filters to the annotation viewer 
- Addresses https://github.com/AVAnnotate/admin-client/issues/81 updating the background color for the active annotation. 
- Adjusts behavior of player and annotation controls to stick at the top of the page without overlapping at all resolutions (hopefully), addressing https://github.com/AVAnnotate/admin-client/issues/80#issuecomment-2349112807

Adding annotation filters

---

generate-iiif-3-manifests.ts
src/types/iiif.ts

- Better handles projects that are just created
- Add some additional metadata
- Switches to single file manifest outout

Manifest generation fixes

---

generate-iiif-3-manifests.ts

- Changed manifest-generation to read the project file instead of passing params.

Manifest generation updates

---

generate-iiif-3-manifests.ts
src/components/EventViewer/VideoEvent.astro
src/components/Player/index.tsx
src/content/config.ts
src/pages/events/[pageUuid].astro
src/pages/pages/[pageUuid].astro
src/types/index.ts
src/utils/pages.ts

This PR adds the feature that enables captions for videos.  Captions specified in the Admin client will automatically be added to videos.
[screen-capture (12).webm](https://github.com/user-attachments/assets/4323b294-8d3e-47bb-bd67-691d48e44dbb)

Captions in video

---

dynamic-astro-config.js
package-lock.json
package.json
src/components/Header.astro
src/components/Sidebar.tsx
src/components/TableOfContents.astro
src/pages/tags/detail/[category]/[tag].astro
src/pages/tags/detail/[category]/index.astro
src/pages/tags/detail/index.astro
src/pages/tags/index.astro

- Added the [relative-links add-on](https://github.com/ixkaito/astro-relative-links) for Astro. This is needed to make the static site work for retrieving css and such.  No issue found with the Pages build using this.
- Updated all links to function correctly with the static site.

Changes to support static sites

---

dynamic-astro-config.js

A small fix that addresses js files not being loaded.

Offline fix

---

package-lock.json
package.json
src/store.ts

This PR removes the nanostore logger added in #88.

Remove nanostore logger

---

static-site-readme.md

Merge to main

---

src/content/config.ts

Reverts AVAnnotate/project-client#97

Revert "Merge to main"

---

generate-iiif-3-manifests.ts
package-lock.json
package.json
src/types/iiif.ts

This PR alters manifest generation to use URL hash offsets instead of point and range selector to specify annotation time stamps.

Manifest generation fix

---

src/components/TableOfContents.astro

- Addresses: https://github.com/AVAnnotate/admin-client/issues/178

Hide home in ToC on home page

---

generate-iiif-3-manifests.ts
src/components/EventViewer/AnnotationUI/TagFilter.tsx

After testing on a number of IIIF Viewers, some changes to the manifest generation were required.  The generated manifest now works on:
Aviary: https://iiif.aviaryplatform.com/
Mirador: https://liblamp.uwm.edu/IIIF/mirador3.html
Other players are not compliant and we will no longer test against them

Manifest generation improvements

---

generate-iiif-3-manifests.ts

- Fixes events with no AVFile URL crashing during presentation build
- Updates the generated id of the manifest to match the manifest URL

URL and ID fix

---

src/pages/tags/detail/[category]/[tag].astro
src/pages/tags/detail/[category]/index.astro
src/pages/tags/detail/index.astro
src/pages/tags/index.astro

- Addresses https://github.com/AVAnnotate/project-client/issues/139
Offline site was generating incorrect URLs

Offline project tags

---

src/components/IIIFButton/IIIFButton.tsx
src/components/TagUtils/AnnotationSpectrum.astro
src/pages/tags/detail/[category]/[tag].astro
src/pages/tags/detail/[category]/index.astro
src/pages/tags/detail/index.astro
src/utils/tags.ts

- Addresses https://github.com/AVAnnotate/project-client/issues/145

Hide empty spectrums in visualizations

---

src/components/RichText/RichTextElement.astro

- Addresses https://github.com/AVAnnotate/admin-client/issues/308
This is the fix for the rendered client

Fix anchor in client

---

src/components/RichText/RichTextElement.astro
src/style/main.css

Implements the [new features](https://github.com/AVAnnotate/admin-client/pull/321) of the RTE in rendering.

RTE improvements

---

src/components/Sidebar.tsx
src/components/TableOfContents.astro

Updated the ToC component to handle the new ToC depths

New ToC to handle arbitrary depth

---

src/components/Header.astro
src/components/Sidebar.tsx
src/components/TableOfContents.astro
src/utils/pages.ts

- Addresses https://github.com/AVAnnotate/admin-client/issues/333

Fix for showing index when no tags are present

---

generate-iiif-3-manifests.ts
src/components/EventViewer/EventComparison.astro
src/pages/tags/detail/[category]/[tag].astro
src/types/index.ts

Embedded events needed better handling of the new file level types.

AV File Type handling

---

generate-iiif-3-manifests.ts
src/components/EventViewer/EventHeader.astro
src/content/config.ts
src/types/index.ts

Display rights statement if one is available.

Show Rights if available

---

src/components/EventViewer/AudioFile.astro
src/components/EventViewer/EventComparison.astro
src/components/EventViewer/VideoFile.astro
src/components/EventViewer/index.astro

Fixes issue with event comparison.

Fix event compare

---

src/components/EventViewer/AudioFile.astro
src/components/EventViewer/EventHeader.astro
src/components/EventViewer/VideoFile.astro

- Addresses https://github.com/AVAnnotate/admin-client/issues/357

Move rights statement to bottom of the page

---

src/components/EventViewer/AudioFile.astro
src/components/EventViewer/EventHeader.astro
src/components/RichText/RichTextExpanding.astro

This PR attempts to ensure more space on the event screens for annotations on first load. There will probably be some other cases to handle.
- Partially addresses https://github.com/AVAnnotate/admin-client/issues/365

Optimize space

---

src/components/RichText/RichTextElement.astro

- The addresses (7) in https://github.com/AVAnnotate/admin-client/issues/385

Fix for image scaling

---

src/components/Footer.astro
src/layouts/Layout.astro

- This PR addresses the z-index of the footer as we were having scrolling weirdness

Z-index of footer
